# Generated by Django 5.0.6 on 2024-07-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogery',
            new_name='Category',
        ),
    ]
